<html>
<head>
<title>TestNG:  Default test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Default test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>9/0/0</td>
</tr><tr>
<td>Started on:</td><td>Fri Apr 14 17:23:02 MSK 2017</td>
</tr>
<tr><td>Total time:</td><td>2 seconds (2748 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.authoriseUserReturnNullTest()'><b>authoriseUserReturnNullTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.authoriseUserSuccessTest()'><b>authoriseUserSuccessTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.changePswdSuccessTest()'><b>changePswdSuccessTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.editProfileSuccessTest()'><b>editProfileSuccessTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.editProfileThrowsDuplicatedKeyExceptionTest()'><b>editProfileThrowsDuplicatedKeyExceptionTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td><div><pre>org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ?]; Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:894)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:287)
	at com.epam.apartment.dao.impl.JdbcUserDao.editProfile(JdbcUserDao.java:108)
	at com.epam.apartment.dao.UserDaoTest.editProfileThrowsDuplicatedKeyExceptionTest(UserDaoTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:652)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.table.Table.updateRows(Table.java:508)
	at org.h2.command.dml.Update.update(Update.java:145)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 32 more
</pre></div><a href='#' onClick='toggleBox("stack-trace238564722", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace238564722'><pre>org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ?]; Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:894)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:287)
	at com.epam.apartment.dao.impl.JdbcUserDao.editProfile(JdbcUserDao.java:108)
	at com.epam.apartment.dao.UserDaoTest.editProfileThrowsDuplicatedKeyExceptionTest(UserDaoTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:652)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;alesnax@gmail.com&apos;, 1)&quot;; SQL statement:
UPDATE USERS SET U_EMAIL = ?, U_NAME = ?, U_SURNAME = ? WHERE U_ID = ? [23505-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.table.Table.updateRows(Table.java:508)
	at org.h2.command.dml.Update.update(Update.java:145)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 32 more
</pre></div></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.registerNewUserSuccessTest()'><b>registerNewUserSuccessTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.registerNewUserWithSameEmailTest()'><b>registerNewUserWithSameEmailTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td><div><pre>org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?)]; Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:894)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:287)
	at com.epam.apartment.dao.impl.JdbcUserDao.registerNewUser(JdbcUserDao.java:78)
	at com.epam.apartment.dao.UserDaoTest.registerNewUserWithSameEmailTest(UserDaoTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:652)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 32 more
</pre></div><a href='#' onClick='toggleBox("stack-trace999736366", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace999736366'><pre>org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?)]; Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:894)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:287)
	at com.epam.apartment.dao.impl.JdbcUserDao.registerNewUser(JdbcUserDao.java:78)
	at com.epam.apartment.dao.UserDaoTest.registerNewUserWithSameEmailTest(UserDaoTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:652)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: &quot;U_EMAIL_UNIQUE_INDEX_4 ON PUBLIC.USERS(U_EMAIL) VALUES (&apos;qnewemail@gmail.com&apos;, 14)&quot;; SQL statement:
INSERT INTO USERS (U_EMAIL, U_NAME, U_SURNAME, U_PASSWORD, U_BIRTHDAY) VALUES (?, ?, ?, ?, ?) [23505-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:704)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 32 more
</pre></div></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.restorePswdSuccessTest()'><b>restorePswdSuccessTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
<tr>
<td title='com.epam.apartment.dao.UserDaoTest.restorePswdWithNotFoundEmailTest()'><b>restorePswdWithNotFoundEmailTest</b><br>Test class: com.epam.apartment.dao.UserDaoTest</td>
<td></td>
<td>0</td>
<td>com.epam.apartment.dao.UserDaoTest@77f99a05</td></tr>
</table><p>
</body>
</html>